name: Commit Bot

on:
  schedule:
    # Runs every day at 06:00 UTC (09:00 Nairobi). Change cron if you want.
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      backfill_days:
        description: 'How many past days to populate (0 = only today)'
        required: false
        default: '0'
      min_commits:
        description: 'Minimum commits per day'
        required: false
        default: '7'
      max_commits:
        description: 'Maximum commits per day'
        required: false
        default: '12'

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git identity
        run: |
          git config --global user.name "${{ secrets.GH_AUTHOR_NAME }}"
          git config --global user.email "${{ secrets.GH_AUTHOR_EMAIL }}"

      - name: Make randomized commits (spread out across day, supports backfill)
        env:
          BACKFILL_DAYS: ${{ github.event.inputs.backfill_days || '0' }}
          MIN_COMMITS: ${{ github.event.inputs.min_commits || '7' }}
          MAX_COMMITS: ${{ github.event.inputs.max_commits || '12' }}
        run: |
          set -euo pipefail
          FILE="contrib_log.txt"
          backfill=${BACKFILL_DAYS}
          minc=${MIN_COMMITS}
          maxc=${MAX_COMMITS}

          echo "Backfill days: $backfill  min:$minc max:$maxc"

          for offset in $(seq ${backfill} -1 0); do
            day=$(date -u -d "$offset days ago" +%Y-%m-%d)
            range=$((maxc - minc + 1))
            commits=$(( (RANDOM % range) + minc ))
            echo "Creating $commits commits for $day"

            # Pick random times across the 24 hours (avoid clustering)
            for i in $(seq 1 $commits); do
              hh=$(printf "%02d" $(( RANDOM % 24 )))
              mm=$(printf "%02d" $(( RANDOM % 60 )))
              ss=$(printf "%02d" $(( RANDOM % 60 )))
              ts="${day}T${hh}:${mm}:${ss}Z"

              echo "Automated entry ${ts} - $RANDOM" >> "$FILE"
              git add "$FILE"
              GIT_AUTHOR_DATE="$ts" GIT_COMMITTER_DATE="$ts" git commit -m "chore: automated commit ${ts}" || echo "no changes"
            done
          done

      - name: Push commits
        run: |
          git push origin HEAD:main
