name: Random Commits Bot

on:
  schedule:
    - cron: "0 8-20 * * *"   # runs hourly between 8 AM and 8 PM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set git identity
        run: |
          git config --global user.name "${{ secrets.GH_AUTHOR_NAME }}"
          git config --global user.email "${{ secrets.GH_AUTHOR_EMAIL }}"

      - name: Make randomized commits
        run: |
          NUM=$(( ( RANDOM % 6 ) + 7 )) # 7–12 commits
          for i in $(seq 1 $NUM); do
            echo "Automated entry $(date) - $RANDOM" >> contrib_log.txt
            git add contrib_log.txt
            git commit -m "chore: automated commit $i"
          done

      - name: Push changes
        run: git push origin HEAD:main
